# Support custom base image
{% if base_image %}
FROM {{ base_image }}
{% elif base_image_default %}
FROM {{ base_image_default }}
{% else %}
FROM agentkit-prod-public-cn-beijing.cr.volces.com/base/py-simple:python{{ language_version }}-bookworm-slim-latest
{% endif %}

ENV UV_SYSTEM_PYTHON=1 UV_COMPILE_BYTECODE=1 PYTHONUNBUFFERED=1 DOCKER_CONTAINER=1

{% if dependencies_file %}
{% if dependencies_install_path %}
COPY {{ dependencies_install_path }} {{ dependencies_install_path }}
{% else %}
COPY {{ dependencies_file }} {{ dependencies_file }}
{% endif %}
{% endif %}

{% if dependencies_file or observability_enabled %}
RUN {% if dependencies_file %}{% if dependencies_install_path %}uv pip install {{ dependencies_install_path }}{% else %}uv pip install -r {{ dependencies_file }}{% endif %}{% endif %}{% if observability_enabled %}{% if dependencies_file %} && \
    {% endif %}{% endif %}
{% endif %}

{% if build_script %}
COPY {{ build_script }} /tmp/build_script.sh
RUN chmod +x /tmp/build_script.sh && /tmp/build_script.sh && rm /tmp/build_script.sh
{% endif %}

EXPOSE 8000

WORKDIR /app

# Copy entire project
{% if not dependencies_install_path or dependencies_install_path != '.' %}
COPY . .
{% endif %}

CMD ["python", "-m", "{{ agent_module_path }}"]
